2:
  rd_cyc: 3
  wr_cyc: 55
  r_pj: 156
  w_pj: 156
  leak_mw: 13.617

32:
  rd_cyc: 9
  wr_cyc: 58
  r_pj: 389
  w_pj: 384
  leak_mw: 94.476

128:
  rd_cyc: 26
  wr_cyc: 67
  r_pj: 685
  w_pj: 667
  leak_mw: 185.785